version: '3'
services:
  personalSiteDB:
    image: postgres
    restart: always
    volumes:
      - ./docker/data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: timtran
      POSTGRES_DB: personalsite
    ports:
      - '3003:5432'

  app:
    container_name: tim
    restart: always
    build: .
    ports:
      - '1128:1128'
    links:
      - personalSiteDB
